import react from 'react'
import Header from "./Home/Header"
import Footer from "./Home/Footer"

const PrivacyPolicy = () => {
    return (
        <>
            <Header></Header>
            <div className='mx-28'>
                <h2 className="font-semibold text-3xl py-10">Privacy Policy</h2>
                <p className='leading-7'>Last updated: 06 April 2024 <br />
                This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You. <br />
                We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>

                <h3 className='font-medium text-2xl'>Interpretation and Definitions</h3>
                
                <h4 className="py-10 font-bold text-2xl">Interpretation</h4>
                <p className='py-2'>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>

                <h4 className="pb-10 font-bold text-xl">Definitions</h4>
                <p>For the purposes of this Privacy Policy:</p>
                <ul className='list-disc px-8 py-3'>
                    <li>Account means a unique account created for You to access our Service or parts of our Service.</li>
                    <li>Company (referred to as either 'the Company', 'We', 'Us' or 'Our' in this Agreement) refers to EZ.Wears, .</li>
                    <li>Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                    <li>Country refers to: India</li>
                    <li>Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                    <li>Personal Data is any information that relates to an identified or identifiable individual.</li>
                    <li>Service refers to the Website.</li>
                    <li>Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
                    <li>Third-party Social Media Service refers to any website or any social network website through which a User can log in or create an account to use the Service.</li>
                    <li>Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                    <li>Website refers to EZ.Wears, accessible from ezwears.in</li>
                    <li>You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                </ul>
                
                <h3 className='font-medium text-2xl py-5'>Collecting and Using Your Personal Data</h3>
                
                <h4 className="py-10 font-bold text-2xl">Types of Data Collected</h4>
                
                <h4 className="pb-10 font-bold text-xl">Personal Data</h4>
                <p className='py-2'>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
                <ul className='list-disc px-8 py-3'>
                    <li>Email address</li>
                    <li>First name and last name</li>
                    <li>Phone number</li>
                    <li>Address, State, Province, ZIP/Postal code, City</li>
                    <li>Usage Data</li>
                </ul>
                
                <h4 className="py-10 font-bold text-xl">Usage Data</h4>
                <p className='leading-7'>Usage Data is collected automatically when using the Service. <br />
                Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data. <br />
                When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data. <br />
                We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
                
                <h4 className="pb-10 font-bold text-xl">Tracking Technologies and Cookies</h4>
                <p className='py-2'>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
                <ul className='list-disc px-8 py-3'>
                    <li>Cookies or Browser Cookies. A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
                    <li>Flash Cookies. Certain features of our Service may use local stored objects (or Flash Cookies) to collect and store information about Your preferences or Your activity on our Service. Flash Cookies are not managed by the same browser settings as those used for Browser Cookies. For more information on how You can delete Flash Cookies, please read 'Where can I change the settings for disabling, or deleting local shared objects?' available at https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_</li>
                    <li>Web Beacons. Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
                </ul>
                <br />
                <p className='leading-7'>Cookies can be 'Persistent' or 'Session' Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. <br />
                We use both Session and Persistent Cookies for the purposes set out below:</p>
                <ul className='list-disc px-8 py-3'>
                    <li>Necessary / Essential Cookies Type: Session Cookies Administered by: Us Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</li>
                    <li>Cookies Policy / Notice Acceptance Cookies Type: Persistent Cookies Administered by: Us Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</li>
                    <li>Functionality Cookies Type: Persistent Cookies Administered by: Us Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</li>
                </ul>
                <p className='pt-8'>For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>
                

            </div>
            <Footer></Footer>
        </>
    )
}

export default PrivacyPolicy
